<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBMe0xd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBMe0xd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBMe0xd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBMe0xd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKBMe0xd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KBMe0xd',
    'container.build_id' => 'b1b3f8fd',
    'container.build_time' => 1623077669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBMe0xd');
