<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Jub9D5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Jub9D5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Jub9D5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Jub9D5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0Jub9D5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0Jub9D5',
    'container.build_id' => '041235e5',
    'container.build_time' => 1622139968,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Jub9D5');
